steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_CMS_URL=https://truzon-backend-715189721854.asia-south1.run.app'
      - '-t'
      - 'asia-south1-docker.pkg.dev/truzonhomescom/cloud-run-source-deploy/truzonhomes:latest'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/truzonhomescom/cloud-run-source-deploy/truzonhomes:latest'