import projAzure from "@/public/images/placeholders/proj-azure.png";
import projElysian from "@/public/images/placeholders/proj-elysian.png";
import projGrand from "@/public/images/placeholders/proj-grand.png";
import projRv from "@/public/images/placeholders/proj-rv.png";
import projSneha from "@/public/images/placeholders/proj-sneha.png";
import projRainbow from "@/public/images/placeholders/proj-rainbow.png";
import projHeaven from "@/public/images/placeholders/proj-heaven.png";
import type { Property } from "@/modules/properties/types";

export const PROPERTIES: Property[] = [
  {
    id: "azure-heights",
    name: "The Azure Heights",
    city: "Hyderabad",
    location: "Banjara Hills, Hyderabad",
    type: "Apartments",
    tagText: "EXCLUSIVE",
    tagBg: "#4c7d2e",
    tagColor: "#ffffff",
    statusText: "Ready to Move",
    specA: "4 BHK",
    specB: "3500 Sq.Ft",
    areaSqft: 3500,
    bedsOptions: ["4"],
    price: "₹4.5 Cr+",
    budgetBracket: "2to5",
    signature: true,
    image: projAzure,
  },
  {
    id: "elysian-woods",
    name: "Elysian Woods",
    city: "Bangalore",
    location: "Whitefield, Bangalore",
    type: "Villas",
    tagText: "UNDER CONSTRUCTION",
    tagBg: "#16264d",
    tagColor: "#ffffff",
    statusText: "BHK 3, 4",
    specA: "Villa",
    specB: "5200 Sq.Ft",
    areaSqft: 5200,
    bedsOptions: ["3", "4"],
    price: "₹8.2 Cr+",
    budgetBracket: "5to10",
    signature: true,
    image: projElysian,
  },
  {
    id: "grand-estate",
    name: "The Grand Estate",
    city: "Hyderabad",
    location: "Kokapet, Hyderabad",
    type: "Plots",
    tagText: "LIMITED PLOTS",
    tagBg: "#d4a537",
    tagColor: "#12172b",
    statusText: "DTCP Approved",
    specA: "Residential Plot",
    specB: "400 Sq.Yds",
    areaSqft: 3600,
    bedsOptions: null,
    price: "₹2.1 Cr+",
    budgetBracket: "2to5",
    signature: true,
    image: projGrand,
  },
  {
    id: "rv-green-park",
    name: "RV Green Park",
    city: "Hyderabad",
    location: "Shankarpally, Hyderabad",
    type: "Farm Lands",
    tagText: "NEW LAUNCH",
    tagBg: "#4c7d2e",
    tagColor: "#ffffff",
    statusText: "Open Plots",
    specA: "Farm Land",
    specB: "1 Acre Plots",
    areaSqft: 43560,
    bedsOptions: null,
    price: "₹95 L+",
    budgetBracket: "under2",
    signature: false,
    image: projRv,
  },
  {
    id: "sneha-villas",
    name: "Sneha Villas",
    city: "Hyderabad",
    location: "Kompally, Hyderabad",
    type: "Villas",
    tagText: "FAST SELLING",
    tagBg: "#d4a537",
    tagColor: "#12172b",
    statusText: "BHK 3",
    specA: "Villa",
    specB: "2800 Sq.Ft",
    areaSqft: 2800,
    bedsOptions: ["3"],
    price: "₹3.2 Cr+",
    budgetBracket: "2to5",
    signature: false,
    image: projSneha,
  },
  {
    id: "rainbow-villas",
    name: "Rainbow Villas",
    city: "Hyderabad",
    location: "Adibatla, Hyderabad",
    type: "Ind. Houses",
    tagText: "DTCP APPROVED",
    tagBg: "#16264d",
    tagColor: "#ffffff",
    statusText: "Ready to Move",
    specA: "Independent House",
    specB: "2200 Sq.Ft",
    areaSqft: 2200,
    bedsOptions: ["3"],
    price: "₹1.8 Cr+",
    budgetBracket: "under2",
    signature: false,
    image: projRainbow,
  },
  {
    id: "heaven-city",
    name: "Heaven City",
    city: "Hyderabad",
    location: "Ranjole, Zaheerabad",
    type: "Plots",
    tagText: "NEW LAUNCH",
    tagBg: "#4c7d2e",
    tagColor: "#ffffff",
    statusText: "DTCP Approved",
    specA: "Residential Plot",
    specB: "150-300 Sq.Yds",
    areaSqft: 1350,
    bedsOptions: null,
    price: "₹28 L+",
    budgetBracket: "under2",
    signature: false,
    image: projHeaven,
  },
];
